// <auto-generated />
namespace POS_System_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supplier_class_remove_and_customer_class_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supplier_class_remove_and_customer_class_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201802271831566_supplier_class_remove_and_customer_class_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
