// <auto-generated />
namespace POS_System_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Delete_and_Remove_CustomerName_from_SalesClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Delete_and_Remove_CustomerName_from_SalesClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201802242109574_Add_Delete_and_Remove_CustomerName_from_SalesClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
